export const feedbackDefs ={
    water: [
      'WATER_TRAIL/WATER_TRAIL',
      'WATER_TRAIL/ABC_WATER_PROGRAMME',
      'WATER_TRAIL/WATER_FEATURE',
      'WATER_TRAIL/BIO_RETENTION_BASIN',
      'WATER_TRAIL/FUTURE_TECHNOLOGIES_1',
      'WATER_TRAIL/FUTURE_TECHNOLOGIES_2',
      'WATER_TRAIL/FUTURE_TECHNOLOGIES_3'
    ],
    bike: ['WELLNESS_TRAIL/WELLNESS_TRAIL'],
    library: [
      'WELLNESS_TRAIL/LIGHTING',
      'WELLNESS_TRAIL/AIR'
    ]
  }
 