export const feedbackDefs = {
  'WATER_TRAIL/WATER_TRAIL': 'water',
  'WATER_TRAIL/ABC_WATER_PROGRAMME': 'water',
  'WATER_TRAIL/WATER_FEATURE': 'water',
  'WATER_TRAIL/BIO_RETENTION_BASIN': 'water',
  'WATER_TRAIL/FUTURE_TECHNOLOGIES_1': 'water',
  'WATER_TRAIL/FUTURE_TECHNOLOGIES_2': 'water',
  'WATER_TRAIL/FUTURE_TECHNOLOGIES_3': 'water',

  'WELLNESS_TRAIL/WELLNESS_TRAIL': 'bike',

  'WELLNESS_TRAIL/LIGHTING': "library",
  'WELLNESS_TRAIL/AIR': 'library',

  'WELLNESS_TRAIL/SUSTAINABLE_NUS': 'l3open',
  'WELLNESS_TRAIL/MOVEMENT': 'l3open',

  'WELLNESS_TRAIL/FUTURE_TECHNOLOGIES_1': 'exhibition',
  'WELLNESS_TRAIL/FUTURE_TECHNOLOGIES_2': 'exhibition',

  'WELLNESS_TRAIL/FUTURE_TECHNOLOGIES_3': 'beehub',

  'TROPICAL_ARCHITECTURE_TRAIL/TROPICAL_ARCHITECTURE_TRAIL': 'l4open',
  'TROPICAL_ARCHITECTURE_TRAIL/BUILDING_FORM': 'l4open',
  'TROPICAL_ARCHITECTURE_TRAIL/ENVELOPE_DESIGN': 'l4open',
  'TROPICAL_ARCHITECTURE_TRAIL/CROSS_VENTILATION': 'l4open',
  'TROPICAL_ARCHITECTURE_TRAIL/LANDSCAPE_DESIGN': 'l4open',
  'TROPICAL_ARCHITECTURE_TRAIL/FUTURE_TECHNOLOGIES_2': 'l4open',
  'TROPICAL_ARCHITECTURE_TRAIL/FUTURE_TECHNOLOGIES_3': 'l4open',

  'TROPICAL_ARCHITECTURE_TRAIL/FUTURE_TECHNOLOGIES_1': 'l4studio',

  'HYBRID_COOLING_TRAIL/HYBRID_COOLING_TRAIL': 'l5open',

  'HYBRID_COOLING_TRAIL/ADAPTIVE_COMFORT' : 'l5east',
  'HYBRID_COOLING_TRAIL/MIXED_MODE': 'l5east',

  'HYBRID_COOLING_TRAIL/ENHANCED_IEQ': 'l5west',
  'HYBRID_COOLING_TRAIL/FUTURE_TECHNOLOGIES_1': 'l5west',
  'HYBRID_COOLING_TRAIL/FUTURE_TECHNOLOGIES_2': 'l5west',
  'HYBRID_COOLING_TRAIL/FUTURE_TECHNOLOGIES_3': 'l5west',

  'NET_ZERO_ENERGY_TRAIL/NET_ZERO_ENERGY_TRAIL': 'l6open',

  'NET_ZERO_ENERGY_TRAIL/ENERGY_GENERATION': 'l6studio',
  'NET_ZERO_ENERGY_TRAIL_DEMAND_REDUCTION': 'l6studio',
  'NET_ZERO_ENERGY_TRAIL/CO_WORKING': 'l6studio',
  'NET_ZERO_ENERGY_TRAIL/FUTURE_TECHNOLOGIES_1': 'l6studio',
  'NET_ZERO_ENERGY_TRAIL/FUTURE_TECHNOLOGIES_2': 'l6studio',
  'NET_ZERO_ENERGY_TRAIL/FUTURE_TECHNOLOGIES_3': 'l6studio',

  'BIOPHILIC_DESIGN_TRAIL/BIOPHILIC_DESIGN_TRAIL': 'l6southOut',
  'BIOPHILIC_DESIGN_TRAIL/NATURE_IN_PLACE': 'l6southOut',
  'BIOPHILIC_DESIGN_TRAIL/NATURE_OF_PLACE': 'l6southOut',

  'BIOPHILIC_DESIGN_TRAIL/MATERIALITY': 'l6eastOut',
  'BIOPHILIC_DESIGN_TRAIL/FUTURE_TECHNOLOGIES_1': 'l6eastOut',
  'BIOPHILIC_DESIGN_TRAIL/FUTURE_TECHNOLOGIES_2': 'l6eastOut',
  'BIOPHILIC_DESIGN_TRAIL/FUTURE_TECHNOLOGIES_3': 'l6eastOut',
}
